[general]
number_of_points=1000
sampling_period=1
time_noise_start=0
number_of_simulations=10
repeatable_noise=true
deterministic_noise=true

[noise_models.ggm]
time_noise_start=0
m=1000
sigma=0.2
kappa=0.1
one_minus_phi=0.01 # GGN_1mphi
dt=1 # Sampling period
units="mom" # TS-format

[noise_models.linear]
time_noise_start=0
m=1000
sigma=0.2
kappa=0.1
one_minus_phi=0.01 # GGN_1mphi
dt=1 # Sampling period
units="mom" # TS-format
